name: JouzuLab
options:
  bundleIdPrefix: com.jouzulab
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    TARGETED_DEVICE_FAMILY: "1,2"

targets:
  JouzuLab:
    type: application
    platform: iOS
    sources:
      - path: JouzuLab
        excludes:
          - "**/.DS_Store"
    resources:
      - path: JouzuLab/Resources
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        INFOPLIST_FILE: JouzuLab/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.jouzulab.app
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        DEVELOPMENT_TEAM: ""
    info:
      path: JouzuLab/Info.plist
      properties:
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
